<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<script src="ftd-style/jquery.js" type="text/javascript"></script> 
<script>
$(document).ready(function() {
      // Tooltip
    $('[title]').hover(function(){
        // on Hover
        var title = $(this).attr('title');
        $(this).data('tipText', title).removeAttr('title');
        $('<p class="tooltip"></p>')
		.html(title)
        .appendTo('body')
        .fadeIn('slow');
    }, function() {
        // Hover out
        $(this).attr('title', $(this).data('tipText'));
        $('.tooltip').remove();
    }).mousemove(function(e) {
        var mousey = e.pageY + 0;
        var mousex = e.pageX + -75;
        $('.tooltip')
        .css({ top: mousey, left: mousex })
    });

});


 
$(document).ready(function(){
  $("#flip").click(function(){
    $("#panel").slideToggle("slow");
  });
});
</script>
<style>
.tooltip {
	display: none;
	position: absolute;
	border-radius: 3px;
	box-shadow: 2px 2px 3px rgba(0, 0, 0, .2);
	background-color: rgba(0, 0, 0, .8);
	border: 1px solid #181818;
	color: #D0D0D0;
	font-size: 11px;
	padding: 6px;
	z-index: 999;
}
.nextlvl {
	margin: 6px 0;
}
.resinfo {
	margin-top: 6px;
	line-height: 16px;
}
.resinfo span {
	margin: 4px 6px;
}
</style>
<?php

if ( !$this->buildProperties['emptyPlace'] )
{
    echo "<div id=\"build\" class=\"gid";
    echo $this->buildProperties['building']['item_id'];
    echo "\">\r\n\t<a href=\"\" onclick=\"return showManual(4, ";
    echo $this->buildProperties['building']['item_id'];
    echo ");\" class=\"build_logo\"><img class=\"building g";
if ($this->buildProperties['building']['item_id'] == '10') {
if ($this->buildProperties['building']['level']>20){
        $this->buildProperties['building']['item_id'] = '38';
}
}
if ($this->buildProperties['building']['item_id'] == '11') {
if ($this->buildProperties['building']['level']>20){
        $this->buildProperties['building']['item_id'] = '39';
}
}
    echo $this->buildProperties['building']['item_id'];
    echo "\" src=\"ftd-style/x.gif\" alt=\"";
    echo htmlspecialchars( constant( "item_".$this->buildProperties['building']['item_id'] ) );
    echo "\" title=\"";
    echo htmlspecialchars( constant( "item_".$this->buildProperties['building']['item_id'] ) );
    echo "\"></a>\r\n\t<h1>";
    echo constant( "item_".$this->buildProperties['building']['item_id'] );
    echo " ";
    echo "<s";
    echo "pan class=\"level\">";
    echo level_lang;
    echo " ";
    echo $this->buildProperties['building']['level'];
    echo "</span></h1>\r\n\t<p class=\"build_desc\"></p>\r\n\t<p style=\"width: 69%; font-weight: bold;\">";
    echo constant( "item_desc_".$this->buildProperties['building']['item_id'] );
    echo "</p>\r\n\t<p></p>\r\n\r\n\t";
    if ( 4 < $this->buildProperties['building']['item_id'] && 0 < $this->buildProperties['building']['update_state'] && $this->buildProperties['building']['level'] == 0 )
    {
        echo "\t<p></p><br/><p></p><p class=\"none\">";
        echo LANGUI_BUILD_T1;
        echo ".</p><p></p><br/><p></p>\r\n\t";
    }
    else
    {
        if ( $this->productionPane )
        {
if ($this->buildProperties['building']['item_id'] != 40) {
            echo "\t<table cellpadding=\"1\" cellspacing=\"1\" id=\"build_value\">\r\n\t\t<tbody>\r\n\t\t\t<tr>\r\n\t\t\t\t<th>";
            echo constant( "item_curprod_".$this->buildProperties['building']['item_id'] );
            echo ":</th>\r\n\t\t\t\t<td><b>";
            echo $this->buildProperties['level']['current_value'];
            echo "</b> ";
            echo constant( "item_unit_".$this->buildProperties['building']['item_id'] );
            echo "</td>\r\n\t\t\t</tr>\r\n\t\t\t";
            if ( $this->buildProperties['building']['level'] < $this->buildProperties['maxLevel'] )
            {
                echo "\t\t\t<tr>\r\n\t\t\t\t<th>";
                echo constant( "item_nextprod_".$this->buildProperties['building']['item_id'] );
                echo " ";
                echo $this->buildProperties['nextLevel'];
                echo ":</th>\r\n\t\t\t\t<td><b>";
                echo $this->buildProperties['level']['value'];
                echo "</b> ";
                echo constant( "item_unit_".$this->buildProperties['building']['item_id'] );
                echo "</td>\r\n\t\t\t</tr>\r\n\t\t\t";
            }


            if ( $this->buildProperties['building']['level']+1 < $this->buildProperties['maxLevel'] )
            {
                echo "\t\t\t<tr>\r\n\t\t\t\t<th>";
                echo constant( "item_nextprod_".$this->buildProperties['building']['item_id'] );
                echo " ";
                echo $this->buildProperties['nexttLevel'];
                echo ":</th>\r\n\t\t\t\t<td><b>";
                echo $this->buildProperties['level']['value2'];
                echo "</b> ";
                echo constant( "item_unit_".$this->buildProperties['building']['item_id'] );
                echo "</td>\r\n\t\t\t</tr>\r\n\t\t\t";
            }

            echo "\t\t</tbody>\r\n\t</table>\r\n\t";
}
if ($this->buildProperties['building']['item_id'] == 40){
echo "<h1>".$this->data['village_name']."</h1>";
}
if ($this->buildProperties['building']['item_id'] == 10 OR $this->buildProperties['building']['item_id'] == 11OR $this->buildProperties['building']['item_id'] == 39 OR $this->buildProperties['building']['item_id'] == 38){

$neededTime1 = $this->getNeededTime2 (1,$this->resources[1]['store_max_limit']);
$a1 = '' . (0 < $neededTime1 ? 'سيمتلئ المخزن بعد <span id="timer1">' . WebHelper::secondstostring ($neededTime1) . '</span> ' . time_hour_lang : "المخزن ممتلئ") . '';
$neededTime2 = $this->getNeededTime2 (2,$this->resources[2]['store_max_limit']);
$a2 = '' . (0 < $neededTime2 ? 'سيمتلئ المخزن بعد <span id="timer1">' . WebHelper::secondstostring ($neededTime2) . '</span> ' . time_hour_lang : "المخزن ممتلئ") . '';
$neededTime3 = $this->getNeededTime2 (3,$this->resources[3]['store_max_limit']);
$a3 = '' . (0 < $neededTime3 ? 'سيمتلئ المخزن بعد <span id="timer1">' . WebHelper::secondstostring ($neededTime3) . '</span> ' . time_hour_lang : "المخزن ممتلئ") . '';
if ($this->resources[4]['calc_prod_rate'] < 0) {
$ll = $this->resources[4]['calc_prod_rate']*-1;
$ss = ceil($this->resources[4]['current_value']/$ll)-1;
if ($ss > 0) {
$a4 = 'سيمضي القمح معك '.$ss.' ساعات';
}else {
$a4 = 'القمح بالسالب لديك حالياً';
}
}else {
$neededTime4 = $this->getNeededTime2 (4,$this->resources[4]['store_max_limit']);
$a4 = '' . (0 < $neededTime4 ? 'سيمتلئ المخزن بعد <span id="timer1">' . WebHelper::secondstostring ($neededTime4) . '</span> ' . time_hour_lang : "المخزن ممتلئ") . '';
}
$r1 = ceil($this->resources[1]['current_value']*100/$this->resources[1]['store_max_limit']);
$r2 = ceil($this->resources[2]['current_value']*100/$this->resources[2]['store_max_limit']);
$r3 = ceil($this->resources[3]['current_value']*100/$this->resources[3]['store_max_limit']);
$r4 = ceil($this->resources[4]['current_value']*100/$this->resources[4]['store_max_limit']);
?>
<p></p><table cellpadding="1" cellspacing="1" id="ressources" class="build_details">
<thead>
<tr>
<th colspan="4"><?php echo $this->data['village_name']; ?></th>
</tr>
</thead>
<tbody>
<tr>
<td><center><img alt="الخشب" src="ftd-style/x.gif" class="r1"></center></td>
<td><center><?php echo $this->txt($r1); ?></center></td>
<td><?php echo $a1; ?></td>
</tr>
<tr>
<td><center><img alt="الخشب" src="ftd-style/x.gif" class="r2"></center></td>
<td><center><?php echo $this->txt($r2); ?></center></td>
<td><?php echo $a2; ?></td>
</tr>
<tr>
<td><center><img alt="الخشب" src="ftd-style/x.gif" class="r3"></center></td>
<td><center><?php echo $this->txt($r3); ?></center></td>
<td><?php echo $a3; ?></td>
</tr>
<tr>
<td><center><img alt="الخشب" src="ftd-style/x.gif" class="r4"></center></td>
<td><center><?php echo $this->txt($r4); ?></center></td>
<td><?php echo $a4; ?></td>
</tr>
</tbody>
</table>
<?php
}
        }
        if ( $this->buildingView != "" && $this->buildProperties['building']['item_id'] != 40)
        {
            require( VIEW_PATH."buildings/".$this->buildingView.".phtml" );
        }
    }
    echo "\t";
    if ( $this->buildProperties['maxLevel'] <= $this->buildProperties['building']['level'] )
    {
        echo "\t<p class=\"none\">";
        echo LANGUI_BUILD_T2;
        echo " ";
        echo constant( "item_".$this->buildProperties['building']['item_id'] );
        echo " ";
        echo LANGUI_BUILD_T3;
        echo "</p>\r\n\t";
    }
    else if ( $this->buildProperties['maxLevel'] <= $this->buildProperties['upgradeToLevel'] && 0 < $this->buildProperties['building']['update_state'] )
    {
        echo "\t<p class=\"none\">";
        echo LANGUI_BUILD_T4;
        echo " ";
        echo constant( "item_".$this->buildProperties['building']['item_id'] );
        echo " ";
        echo LANGUI_BUILD_T3;
        echo "</p>\r\n\t";
    }
    else
    {
        echo "\t<p id=\"contract\">\r\n\t\t<b>";
        echo LANGUI_BUILD_T5;
        echo " </b> ";
        echo LANGUI_BUILD_T6;
        echo " ";
        echo $this->buildProperties['nextLevel'];
        echo ":<br>\r\n\t\t<img class=\"r1\" src=\"ftd-style/x.gif\" alt=\"";
        echo item_title_1;
        echo "\" title=\"";
        echo item_title_1;
        echo "\">";
        echo $this->buildProperties['level']['resources'][1];
        echo " | \r\n\t\t<img class=\"r2\" src=\"ftd-style/x.gif\" alt=\"";
        echo item_title_2;
        echo "\" title=\"";
        echo item_title_2;
        echo "\">";
        echo $this->buildProperties['level']['resources'][2];
        echo " | \r\n\t\t<img class=\"r3\" src=\"ftd-style/x.gif\" alt=\"";
        echo item_title_3;
        echo "\" title=\"";
        echo item_title_3;
        echo "\">";
        echo $this->buildProperties['level']['resources'][3];
        echo " | \r\n\t\t<img class=\"r4\" src=\"ftd-style/x.gif\" alt=\"";
        echo item_title_4;
        echo "\" title=\"";
        echo item_title_4;
        echo "\">";
        echo $this->buildProperties['level']['resources'][4];
        echo " | \r\n\t\t<img class=\"r5\" src=\"ftd-style/x.gif\" alt=\"";
        echo LANGUI_BUILD_T7;
        echo "\" title=\"";
        echo LANGUI_BUILD_T7;
        echo "\">";
        echo $this->buildProperties['level']['people_inc'];
        echo " | \r\n\t\t<img class=\"clock\" src=\"ftd-style/x.gif\" alt=\"";
        echo text_period_lang;
        echo "\" title=\"";
        echo text_period_lang;
        echo "\">";
        echo WebHelper::secondstostring( $this->buildProperties['level']['calc_consume'] );
        echo "\t\t";
        echo $this->getResourceGoldExchange( $this->buildProperties['level']['resources'], $this->buildProperties['building']['item_id'], $this->buildingIndex );
        echo "\t\t<br>";
        echo $this->getActionText( $this->buildProperties['level']['resources'], $this->buildProperties['building']['item_id'] <= 4, TRUE, $this->buildProperties['building']['item_id'] );
        if($this->buildProperties['building']['item_id'] != 40) {
?> | 
<?php
$x_o = $this->buildProperties['building']['level']+1;
for ($x=$x_o; $x<$this->buildProperties['maxLevel']; $x++) {
$gold += $x;

if($gold >= $this->data['gold_num']) {break;}
}
echo '<a name="lvl" href="village1?id='. $this->buildingIndex . '&key=' . md5($this->buildingIndex .'-'. $this->data['update_key']) .'&up&lvl='.$x.'">';
echo "الارتقاء فورا ";
echo 'الى مستوى ' .$x;
echo "</a>";

echo "<img src=\"ftd-style/x.gif\" class=\"gold\" alt=\"ذهب\" title=\"ذهب\"> " . $gold  ;
}
        echo "\t</p>\r\n\t";
    }

    if($this->buildProperties['building']['item_id'] <= 4)
    {
        if($this->showFormDev)
        {
            echo '<br><br>يمكنك الارتقاء فورا لجميع حقول <u>'. constant( "item_".$this->buildProperties['building']['item_id'] ) .'</u>';
            echo ' الى المستوى '. $this->buildProperties['maxLevel'];
            echo ' مقابل <img src="ftd-style/x.gif" class="gold" alt="ذهب" title="ذهب"> '. $this->gold .'<br><br>';

            if($this->data['gold_num'] >= $this->gold)
                echo '<a class="build" href="build?id='. $_GET['id'] .'&max&bid='.$this->buildProperties['building']['item_id'].'">» الارتقاء فورا لجميع الحقول</a>';
            else
                echo '<span class="none">لا تملك ذهب كافي لإتمام العملية</span>';
        }
    }
    echo "</div>\r\n";
}
else
{
    echo "<s";
    echo "cript language=\"JavaScript\" type=\"text/javascript\">\r\nfunction showPane(list) {\r\n\tvar build_list = _('build_list_'+list);\r\n\tvar link = _(list+'_link');\r\n\r\n\tif (build_list.className == 'hide') {\r\n\t\tbuild_list.className = '';\t\t\r\n\t\tlink.innerHTML = '";
    echo LANGUI_BUILD_T8;
    echo "';\r\n\t} else {\r\n\t\tbuild_list.className = 'hide';\r\n\t\tlink.innerHTML = '";
    echo LANGUI_BUILD_T9;
    echo "';\r\n\t}\r\n}\r\n</script>\r\n<div id=\"build\" class=\"gid0\"><h1>";
    echo LANGUI_BUILD_T10;
    echo "</h1>\r\n\r\n";
    foreach ( $this->newBuilds['available'] as $buildArray )
    {

        foreach ( $buildArray as $item_id => $build )
        {


            if($item_id == 45)
            {
                $q1    = 0;
                $level45 = 0;
                $buildings = $this->data['buildings'];
                $buildings = explode(',', $buildings);
                foreach ($buildings as $id => $building)
                {
                    $building = explode(' ', $building);

                    if($building[0] == 1)
                    {
                        $q1 += 1;
                        $level45 += $building[1];
                    }
                }

                $maxL45 = 25 * $q1;
                if($maxL45 != $level45)
                {
                    continue;
                }
            }

            if($item_id == 46)
            {
                $q1    = 0;
                $level46 = 0;
                $buildings = $this->data['buildings'];
                $buildings = explode(',', $buildings);
                foreach ($buildings as $id => $building)
                {
                    $building = explode(' ', $building);

                    if($building[0] == 2)
                    {
                        $q1 += 1;
                        $level46 += $building[1];
                    }
                }

                $maxL46 = 25 * $q1;
                if($maxL46 != $level46)
                {
                    continue;
                }
            }

            if($item_id == 47)
            {
                $q1    = 0;
                $level47 = 0;
                $buildings = $this->data['buildings'];
                $buildings = explode(',', $buildings);
                foreach ($buildings as $id => $building)
                {
                    $building = explode(' ', $building);

                    if($building[0] == 3)
                    {
                        $q1 += 1;
                        $level47 += $building[1];
                    }
                }

                $maxL47 = 25 * $q1;
                if($maxL47 != $level47)
                {
                    continue;
                }
            }

            if ( $this->data['is_special_village'] )
            {
                    if ( $_GET['id'] == 25 || $_GET['id'] == 26 || $_GET['id'] == 29 || $_GET['id'] == 30 || $_GET['id'] == 33 )
                    {
                        if ($item_id != 40)
                        {
                            continue;
                        }
}else {
                        if ($item_id == 40)
                        {
                            continue;
                        }

}
                do
                {
                    if ( $_GET['id'] == 25 || $_GET['id'] == 26 || $_GET['id'] == 29 || $_GET['id'] == 30 || $_GET['id'] == 33 )
                    {
                        if ( !( $item_id != 40 ) )
                        {
                            break;
                        }
                        else
                        {
                            continue;
                        }
                    }
                    if ( !( $item_id == 40 ) )
                    {
                        break;
                    }
                    continue;
                } while ( 0 );
            }
            if ( $_GET['id'] == 39 && $item_id != 16 )
            {
                continue;
            }
            if ( $_GET['id'] == 40 && $item_id != 31 && $item_id != 32 && $item_id != 33 )
            {
                continue;
            }
            if ( $_GET['id'] != 39 && $_GET['id'] != 40 && ( $item_id == 16 || $item_id == 31 || $item_id == 32 || $item_id == 33 ) )
            {
                continue;
            }
            $neededResources = $build['levels'][0]['resources'];
            echo "<h2>";
$gid = $item_id;
if ($gid == 38) {
$gid= 11;
}
if ($gid== 39) {
$gid= 10;
}

            echo constant( "item_".$gid);
            echo "</h2>\r\n<table class=\"new_building\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td class=\"desc\"><p>";
            echo constant( "item_desc_".$gid);
            echo "</p></td>\r\n\t\t\t<td rowspan=\"3\" class=\"bimg\">\r\n\t\t\t\t<a href=\"#\" onclick=\"return showManual(4, ";
            echo $item_id;
            echo ");\"><img class=\"building g";
            echo $gid;
            echo "\" src=\"ftd-style/x.gif\" alt=\"";
            echo htmlspecialchars( constant( "item_".$item_id ) );
            echo "\" title=\"";
            echo htmlspecialchars( constant( "item_".$item_id ) );
            echo "\"></a>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"res\">\r\n\t\t\t\t<img class=\"r1\" src=\"ftd-style/x.gif\" alt=\"";
            echo item_title_1;
            echo "\" title=\"";
            echo item_title_1;
            echo "\">";
            echo $neededResources[1];
            echo " | \r\n\t\t\t\t<img class=\"r2\" src=\"ftd-style/x.gif\" alt=\"";
            echo item_title_2;
            echo "\" title=\"";
            echo item_title_2;
            echo "\">";
            echo $neededResources[2];
            echo " | \r\n\t\t\t\t<img class=\"r3\" src=\"ftd-style/x.gif\" alt=\"";
            echo item_title_3;
            echo "\" title=\"";
            echo item_title_3;
            echo "\">";
            echo $neededResources[3];
            echo " | \r\n\t\t\t\t<img class=\"r4\" src=\"ftd-style/x.gif\" alt=\"";
            echo item_title_4;
            echo "\" title=\"";
            echo item_title_4;
            echo "\">";
            echo $neededResources[4];
            echo " | \r\n\t\t\t\t<img class=\"r5\" src=\"ftd-style/x.gif\" alt=\"";
            echo LANGUI_BUILD_T7;
            echo "\" title=\"";
            echo LANGUI_BUILD_T7;
            echo "\">";
            echo $build['levels'][0]['people_inc'];
            echo " | \r\n\t\t\t\t<img class=\"clock\" src=\"ftd-style/x.gif\" alt=\"";
            echo text_period_lang;
            echo "\" title=\"";
            echo text_period_lang;
            echo "\">";
            echo WebHelper::secondstostring( $build['levels'][0]['time_consume'] / $GLOBALS['AppConfig']['Game']['speed_b'] * ( $this->data['time_consume_percent'] / 100 ) );
            echo "\t\t\t\t";
            echo $this->getResourceGoldExchange( $neededResources, $item_id, $this->buildingIndex );
            echo "\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"link\">";
            echo $this->getActionText( $neededResources, FALSE, FALSE, $item_id );
            echo "</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n";
        }
    }
    echo "\r\n";
    if ( $_GET['id'] != 39 && $_GET['id'] != 40 && !( $this->data['is_special_village'] && ( $_GET['id'] == 25 || $_GET['id'] == 26 || $_GET['id'] == 29 || $_GET['id'] == 30 || $_GET['id'] == 33 ) ) )
    {

        echo "<p class=\"switch\"><a id=\"soon_link\" href=\"javascript:showPane('soon');\">";
        echo LANGUI_BUILD_T9;
        echo "</a></p>\r\n<div id=\"build_list_soon\" class=\"hide\">\r\n\r\n";
        foreach ( $this->newBuilds['soon'] as $buildArray )
        {
            foreach ( $buildArray as $item_id => $build )
            {

                echo "<h2>";
                echo constant( "item_".$item_id );
                echo "</h2>\r\n<table class=\"new_building\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td class=\"desc\"><p>";
                echo constant( "item_desc_".$item_id );
                echo "</p></td>\r\n\t\t\t<td rowspan=\"3\" class=\"bimg\">\r\n\t\t\t\t<a href=\"#\" onclick=\"return showManual(4, ";
                echo $item_id;
                echo ");\"><img class=\"building g";
                echo $item_id;
                echo "\" src=\"ftd-style/x.gif\" alt=\"";
                echo htmlspecialchars( constant( "item_".$item_id ) );
                echo "\" title=\"";
                echo htmlspecialchars( constant( "item_".$item_id ) );
                echo "\"></a>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"requ\">";
                echo LANGUI_BUILD_T11;
                echo ":</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>\r\n\t\t\t";
                $flag = FALSE;
                foreach ( $build['pre_requests'] as $reqId => $reqValue )
                {
                    echo "\t\t\t";
                    if ( $flag )
                    {
                        echo ", ";
                    }
                    echo "<a href=\"#\" onclick=\"return showManual(4,";
                    echo $reqId;
                    echo ");\">";
                    if ( $reqValue == NULL )
                    {
                        echo "<strike>";
                    }
                    echo constant( "item_".$reqId );
                    if ( $reqValue == NULL )
                    {
                        echo "</strike>";
                    }
                    echo "</a>";
                    if ( $reqValue != NULL )
                    {
                        echo "<s";
                        echo "pan title=\"";
                        echo $build['pre_requests_dependencyCount'][$reqId] < 0 ? ">" : "+".$build['pre_requests_dependencyCount'][$reqId];
                        echo "\"> ";
                        echo level_lang;
                        echo " ";
                        echo $reqValue;
                    }
                    echo "</span>\r\n\t\t\t";
                    $flag = TRUE;
                }
                echo "\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n";
            }
        }

        if($maxL45 != $level45)
        {
                echo '<h2>'. item_45 .'</h2>';
                echo '<table class="new_building" cellpadding="1" cellspacing="1">
    <tbody>
        <tr>
            <td class="desc"><p>'.item_desc_45.'</p></td>
            <td rowspan="3" class="bimg">
                <a href="#" onclick="return showManual(4, 7);"><img class="building g45" src="ftd-style/x.gif" alt="'. item_45 .'" title="'. item_45 .'"></a>
            </td>
        </tr>
        <tr>
            <td class="requ">الشروط:</td>
        </tr>
        <tr>
            <td>
                        جميع <a href="#" onclick="return showManual(4,1);"> حقول الخشب</a><span title="+25"> المستوى 25</span>
                        </td>
        </tr>
    </tbody>
</table>';
        }
        if($maxL46 != $level46)
        {
                echo '<h2>'. item_46 .'</h2>';
                echo '<table class="new_building" cellpadding="1" cellspacing="1">
    <tbody>
        <tr>
            <td class="desc"><p>'.item_desc_46.'</p></td>
            <td rowspan="3" class="bimg">
                <a href="#" onclick="return showManual(4, 7);"><img class="building g46" src="ftd-style/x.gif" alt="'. item_46 .'" title="'. item_46 .'"></a>
            </td>
        </tr>
        <tr>
            <td class="requ">الشروط:</td>
        </tr>
        <tr>
            <td>
                        جميع <a href="#" onclick="return showManual(4,2);"> حقول الطين</a><span title="+25"> المستوى 25</span>
                        </td>
        </tr>
    </tbody>
</table>';
        }
        if($maxL47 != $level47)
        {
                echo '<h2>'. item_47 .'</h2>';
                echo '<table class="new_building" cellpadding="1" cellspacing="1">
    <tbody>
        <tr>
            <td class="desc"><p>'.item_desc_47.'</p></td>
            <td rowspan="3" class="bimg">
                <a href="#" onclick="return showManual(4, 7);"><img class="building g47" src="ftd-style/x.gif" alt="'. item_47 .'" title="'. item_45 .'"></a>
            </td>
        </tr>
        <tr>
            <td class="requ">الشروط:</td>
        </tr>
        <tr>
            <td>
                        جميع <a href="#" onclick="return showManual(4,3);"> حقول الحديد</a><span title="+25"> المستوى 25</span>
                        </td>
        </tr>
    </tbody>
</table>';
        }

        echo "</div>\r\n";
    }
    echo "</div>\r\n";
}
if (($this->appConfig['system']['server_start'] > date('Y/m/d H:i:s'))){
?>
<center><p style="font-size:20px;">بقي على انطلاق اللعب</p>
<span id="timer1" style="font-size: 22px; color: orange; font-weight: bold; text-shadow: 1px 1px #000;"><?php echo TimeAgo(strtotime($this->appConfig['system']['server_start']) - time()); ?></span>
<?php
}
?>
</body>
</html>